### ISSUE TITLE
The refresh token is invalid

### ISSUE THREAD

**Issue by Fanyatsu** [circleguard/ossapi#42]
Hi. I am using your library in my discord bot. Everything is fine, but when like ~24 hours passing since token generation, active bot instance throws this:
> Command raised an exception: PermissionError: [Errno 13] Permission denied: '/home/ubuntu/.local/lib/python3.9/site-packages/ossapi/6509661aa4e496a8b6011af2c71339a22d8752ea2033089aa384c22aeab15de8.pickle'

Then, after bot restart, it changes to:

> Command raised an exception: InvalidClientIdError: (invalid_request) The refresh token is invalid.
File is still present in the folder /home/ubuntu/.local/lib/python3.9/site-packages/ossapi

So every day i need to launch my code on Windows (my server has no GUI and browser cant be open there), then go into AppData to grab that file and upload on the server. Its annoying.

Here is some technical information:
OS: Linux (Ubuntu 18.04)
Python version: 3.9
ossapi version: 2.2.1 (latest at the moment)
nextcord version: 2.0.0a4 (latest at the moment)

Help me please, i really want to continue using ossapi

**Comment by tybug** [comment]
Do you have full stacktraces for either of these errors? I'm especially confused/worried because it's raising an `InvalidClientIdError` and then complaining that the \*refresh token* is invalid. 

Regardless, it seems like the root cause here is going to be the permission denied error. It seemingly tries (and succeeds) in requesting a new access token from the api, but then can't write that back to the credentials file (`6509661aa4e496a8b6011af2c71339a22d8752ea2033089aa384c22aeab15de8.pickle`), and so the next time the bot tries to access that file - expecting valid credentials - it finds old, expired ones. This might be a problem on your end where your script doesn't have permission to write to that location - though why it would only fail when refreshing the token and not when originally generating it, I don't know.

You could also try writing the saved credentials to a local directory, where you can guarantee you have write permissions, with `OssapiV2(token_directory="./creds")` or some other local dir. `token_directory` will cause those token (ie credential) files to be written to the given directory instead of the site-packages directory.

**Comment by Fanyatsu** [comment]
@tybug I have no full stacktraces, met python language exactly week ago and made lots of features including various osu interaction things. However im still a newbie to py.
Thank you for pointing on "token_directory". My user indeed has no root access and rights to make edits there, so its big help from you ❤️
Good luck in development!
