### ISSUE TITLE
ValueError: '' is not a valid GameMode

### ISSUE THREAD

**Issue by Swyreee** [circleguard/ossapi#50]
When I use the following code snippet, a `ValueError` exception is thrown:
```python
api = OssapiV2(Config.OSU["client_id"], Config.OSU["client_secret"])

# Both don't work
api.user(username, "", UserLookupKey.USERNAME)
api.user(username, None, UserLookupKey.USERNAME)
```
But the documentation [specifies otherwise](https://osu.ppy.sh/docs/index.html#get-user)

**Comment by Stedoss** [comment]
You should omit the gamemode (2nd parameter) if you want to get the default gamemode (or you should specify it). From your code example you probably want
```py
api.user(username, key=UserLookupKey.USERNAME)
```
you could also write
```py
api.user(username)
api.user(username, GameMode.STD, UserLookupKey.USERNAME)
# different mutations of these
```

**Comment by tybug** [comment]
It’s true that you can omit that parameter, but it’s reasonable to expect that passing `None` would be equivalent to not passing it at all. The reason it’s not is because of some magic on our end which we should fix. 

However, I don’t think that passing the empty string should be accepted as valid (it’s not really equivalent to None).

**Comment by tybug** [comment]
closed by https://github.com/circleguard/ossapi/commit/5cb1df93c8b49a852221cfba8eab81d3b325e01c. Please try ossapi v2.2.4: your second example should work there. It's intentional that the first example (passing an empty string) fails, because the empty string is not a valid gamemode, nor does the empty string represent a null value like `None`. 

If you have a valid argument for the empty string being accepted as a valid gamemode, please let me know :)
