### ISSUE TITLE
Getting information for missing user IDs result in unclosed client sessions

### ISSUE THREAD

**Issue by cocoon333** [circleguard/ossapi#58]
![image](https://user-images.githubusercontent.com/15187455/230234032-ecd65594-c36a-4494-bf3f-062a7c9713fd.png)

Version 3.1.5

**Comment by tybug** [comment]
There are two issues here:
* aiohttp's urls are URL objects instead of strings, so `unqoute` fails and doesn't give the correct error message.
* spurious unclosed client session warnings on error. These are warnings and can be safely ignored, but I've improved our management of the session lifetime to fix this.

I've fixed both issues in f9cbfce.
